apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  data:
    - secretKey: api-token
      remoteRef:
        key: kubernetes/development/traefik/cloudflare-api-token
        property: api-token
