---
# Uncomment to enable automated image updates
# apiVersion: image.toolkit.fluxcd.io/v1beta2
# kind: ImageUpdateAutomation
# metadata:
#   name: flux-system
#   namespace: flux-system
# spec:
#   interval: 30m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   git:
#     checkout:
#       ref:
#         branch: main
#     commit:
#       author:
#         email: fluxcdbot@users.noreply.github.com
#         name: fluxcdbot
#       messageTemplate: |
#         Automated image update
#
#         Automation name: {{ .AutomationObject }}
#
#         Files:
#         {{ range $filename, $_ := .Updated.Files -}}
#         - {{ $filename }}
#         {{ end -}}
#
#         Objects:
#         {{ range $resource, $_ := .Updated.Objects -}}
#         - {{ $resource.Kind }} {{ $resource.Name }}
#         {{ end -}}
#
#         Images:
#         {{ range .Updated.Images -}}
#         - {{.}}
#         {{ end -}}
#     push:
#       branch: main
#   update:
#     path: ./clusters/production
#     strategy: Setters
