apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellystat-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellystat.zech.dev`)
      kind: Rule
      services:
        - name: jellystat
          port: 3000
