apiVersion: v1
kind: ConfigMap
metadata:
  name: proxmox-ca
  namespace: csi-proxmox
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIF8zCCA9ugAwIBAgIBADANBgkqhkiG9w0BAQsFADBtMQswCQYDVQQGEwJBVDET
    MBEGA1UECAwKVm9yYXJsYmVyZzEQMA4GA1UEBwwHU29ubnRhZzEQMA4GA1UECgwH
    SG9tZWxhYjELMAkGA1UECwwCSVQxGDAWBgNVBAMMD0hvbWVsYWIgUm9vdCBDQTAe
    Fw0yNjAxMjgxOTExMjVaFw0zNjAxMjYxOTExMjVaMG0xCzAJBgNVBAYTAkFUMRMw
    EQYDVQQIDApWb3JhcmxiZXJnMRAwDgYDVQQHDAdTb25udGFnMRAwDgYDVQQKDAdI
    b21lbGFiMQswCQYDVQQLDAJJVDEYMBYGA1UEAwwPSG9tZWxhYiBSb290IENBMIIC
    IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA7CLKHmmbmVJvKR2cLvW/ZXx5
    vYuwBo9Gr2/iZrG5ZYIVhG5p9yVR2gseO5S74HVeDwaLIbOtsAo4ucBA0htdlQQq
    O4khIKzE7/sKdL+iPSFxa1wISTENKXseseucDHVccrLcVM459/j2356Nwt764Ya7
    mRFbjAoe1NLsckcKKqO2zP/m+Ty8ZpnUUW9fd2Lm3PwcS2ppKcT1yeFJJdl6vVFQ
    Q8+3NXcGk1j4GEJQxBf3I2UxNNYb5k/PJBGmV9s6uxOosmNjwDM8yYeltibf4jpk
    tnNtmu4geL19wSZCU8nI3/JXmBk8h+lAG9B0hgSEtmih47x1MTZy9pKcayUSYcGE
    jS8jY5VA1JC0p3TkIQJP9HUEKgjW/qmThgUOlmoe2I9nZnK4eEqh7tMo0iJ+Lpau
    tqr3p+Lv1YoDXSykSZede6dvgzo4PfL8us+4QiBWzzzeU99NNlMUgoHMBFGCNpGJ
    NQJhRlEE32G0veY9Bg963oAOjwzSAq4rUD4bH91DdFgEr/WNgv8R8XvoqiWlWtEa
    p4ftAy5J1q13s/McXmgOGUZju37MbTJ8+aXXieYQ8Ektnb8fkKzPjnvKGa/+T9w8
    x41bjc/koE9ZqeoEb+hMhImE9WNjkwuIpFRlVPE1XCjs2inZCM4EJTbSkxQ9/HRd
    iFfISBF0QcTAChsGmykCAwEAAaOBnTCBmjA3BglghkgBhvhCAQ0EKhYoT1BOc2Vu
    c2UgR2VuZXJhdGVkIENlcnRpZmljYXRlIEF1dGhvcml0eTAdBgNVHQ4EFgQU/AWB
    7Y/Q24ZkEujezH4OEmg42X4wHwYDVR0jBBgwFoAU/AWB7Y/Q24ZkEujezH4OEmg4
    2X4wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQEL
    BQADggIBANYLorXh8ikh2MnecJluIEWKdMmldCrCluZ7vzud8jOR+V2uRLWlMNe2
    rAO1oC1KiEYC4lYNYiezGltbPtGVaSUhgpbZ5SOmvx+F0Zsg4pWuX7Whm4T+MXR6
    DoIRSJnEpp20i3mh6ZDt0vxcphfloNNUS5nQLl4O+rxRSpc7Qtj/T2SmR2RFoskF
    sFNb/geV46BbzP2G3tjpkVWjPdBg+clIJePgL4fOoT+RxAzF6eNMBCBCrxo/Hclx
    8h4s5eyz0eELo2VMEqmLblQFagoiQkFwBZ2p3E2HoGA2QCHXcICR/Iu4cN6DH6x4
    Muj4nI93J+7p9XY+6+T4UAqUx5RnoCXlwuFpQkydN1fXmEix0ylfpUImwltd44SP
    spkeoYWBh6BEAZdqk2rMKaxlvzP17o92BinDL+1277D8DVtNfuP1UjBclvcr1t1q
    1ui32SyS3XywkQ+lpwWiflnxDdO7xwdxbixresdkNPdp3xZ2loDdOJiFQF7Zcnx0
    eMzGPh+xcyu7fC02AEUjNsco73IaWE4eoHyCNb7oqALAD8CJV736j+rcmPMu/bJK
    eVamHcPs51+bIzurnMsEgV8OS+UUIY5gHovy+kb4JomjnWkyUUPXKcpeVLkcP1vS
    suGXebXflIZsqVijNFRaWilMYVf3J2TccrqYJNa8NYB4kMhDQ0b5
    -----END CERTIFICATE-----
